global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/bili/**.dart
          - lib/data/**.dart
          - lib/network/**.dart
        options:
          copyWith: false
          #equal: false
          map: false
          to_json: false
          # to_string: false
          when:
            when: false
            maybe_when: false
            when_or_null: false
      
      go_router_builder:
        generate_for:
          include:
            - lib/routing/router.dart

      json_serializable:
        generate_for:
          include:
            - lib/**.dart
            #- lib/bili/search_type.dart
            #- lib/network/retrofit/api_result.dart
            #- lib/network/model/**.dart
          exclude:
            - lib/**.g.dart
            - lib/**.freezed.dart
            - lib/**.config.dart
        options:
          create_to_json: false
          checked: true
          # 序列化嵌套的 Freezed 对象
          # explicit_to_json: true
          # field_rename: snake
      
      retrofit_generator:
        generate_for:
          include:
            - lib/network/retrofit/retrofit_network.dart