name: bilibili
description: Bilibili API wrapper and remote data source.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: "^3.13.2"
  flutter: ">=3.47.2"

resolution: workspace

workspace:
  - bpi

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data: ^1.0.0
  bpi: ^1.0.0
  model: ^1.0.0
  http: ^1.6.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: any

flutter:
  generate: true
