name: datastore
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: "^3.12.2"
  flutter: "3.44.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  model: ^1.0.0
  
  shared_preferences: ^2.5.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
